export {default as GithubIcon} from './github'
export {default as MailIcon} from './mail'
export {default as TwitterIcon} from './twitter'
export {default as LinkedinIcon} from './linkedin'
export {default as FacebookIcon} from './facebook'
export {default as YoutubeIcon} from './youtube'
