name: Lighthouse CI
on: [push]

jobs:
    lhci:
        name: Lighthouse
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js 22.x
              uses: actions/setup-node@v1
              with:
                  node-version: 22.x
            - run: corepack enable
            - run: corepack prepare --activate
            - name: install & build
              run: |
                  pnpm install --frozen-lockfile
                  pnpm build
            - name: run Lighthouse CI
              run: |
                  npm install -g @lhci/cli@0.12.0
                  lhci autorun
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
