name: 'lint & prettier'

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run images
      - run: npm run lint
      - run: npm run prettier
      - run: npm run lint:style
