name: 'lint & prettier'

on:
    push:
        branches-ignore:
            - 'main'

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js ${{ matrix.node-version }}.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: corepack enable
            - run: corepack prepare --activate
            - run: pnpm install --frozen-lockfile
            - run: pnpm lint
            - run: pnpm prettier
            - run: pnpm lint:style
